#!/usr/bin/env node
'use strict';
/**
 * Bundles Shadow's detection engine for environments without Node.
 *
 * The same files that run in the desktop browser are wrapped in a tiny
 * CommonJS shim and emitted as one script that works in:
 *   - mobile Safari (the phone companion app)
 *   - iOS JavaScriptCore (the native app runs the identical logic)
 *
 * Deliberately not a real bundler. The point is that the detection rules on
 * your phone are literally the same source as on the desktop, not a
 * reimplementation that can drift out of step.
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'src', 'main');
const OUT = path.join(__dirname, 'shadow-engine.js');

// Order matters only for readability; the shim resolves lazily.
const MODULES = [
  'soc/data/public-suffixes.js',
  'soc/data/tld-reputation.js',
  'soc/data/brands.js',
  'soc/heuristics/url-heuristics.js',
  'soc/heuristics/content-heuristics.js',
  'soc/heuristics/tls-heuristics.js',
  'soc/scoring.js',
  'firewall/rules.js',
  'firewall/blocklists.js',
  'sandbox/scanner.js',
];

/** Turn a relative require inside `fromId` into a canonical module id. */
function resolveId(fromId, request) {
  if (!request.startsWith('.')) return request;          // a shim, left as-is
  const dir = path.posix.dirname(fromId);
  let id = path.posix.normalize(path.posix.join(dir, request));
  if (!id.endsWith('.js')) id += '.js';
  return id;
}

function build() {
  const parts = [];

  for (const id of MODULES) {
    const file = path.join(SRC, id);
    let source = fs.readFileSync(file, 'utf8');

    // Rewrite relative requires to canonical ids so the shim can find them.
    source = source.replace(/require\((['"])([^'"]+)\1\)/g, (match, quote, request) => {
      const target = resolveId(id, request);
      return `require(${quote}${target}${quote})`;
    });

    parts.push(
      `__define(${JSON.stringify(id)}, function (module, exports, require) {\n`
      + `${source}\n`
      + '});\n');
  }

  const banner = `/* Shadow detection engine.
 * Generated by mobile/build-engine.js from src/main/. Do not edit by hand.
 * Built ${new Date().toISOString()} from ${MODULES.length} modules.
 *
 * Exposes globalThis.ShadowEngine with:
 *   analyzeUrl(url)        -> signal[]
 *   analyzeContent(html, url) -> signal[]
 *   decide(signals, opts)  -> verdict
 *   checkUrl(url, opts)    -> verdict           (url signals + blocklists)
 *   checkPage(html, url, opts) -> verdict       (everything the desktop does)
 *   blocklists             -> Blocklists instance seeded with the built-ins
 */`;

  const shim = `
(function (root) {
  'use strict';

  var __registry = {};
  var __cache = {};

  function __define(id, factory) { __registry[id] = factory; }

  function require(id) {
    // ---- Node built-ins used by the engine, reimplemented for the browser ---
    if (id === 'node:url' || id === 'url') return __nodeUrl;
    if (id === 'fs') return __fsStub;
    if (id === 'path') return __pathStub;
    if (id === 'crypto' || id === 'node:crypto') return __cryptoStub;
    if (id === 'zlib' || id === 'node:zlib') return __zlibStub;
    if (id === 'os' || id === 'node:os') return { tmpdir: function () { return '/tmp'; }, homedir: function () { return '/'; } };

    if (__cache[id]) return __cache[id].exports;
    var factory = __registry[id];
    if (!factory) throw new Error('Shadow engine: no module "' + id + '"');
    var module = { exports: {} };
    __cache[id] = module;
    factory(module, module.exports, require);
    return module.exports;
  }

  // --- punycode decoding, so homograph checks see the real characters ------
  // new URL() converts an internationalised host to its xn-- form, which hides
  // exactly the characters the mixed-script check needs. Node gives us
  // domainToUnicode; browsers do not, so this is RFC 3492 decode.
  var BASE = 36, TMIN = 1, TMAX = 26, SKEW = 38, DAMP = 700, INITIAL_BIAS = 72, INITIAL_N = 128;

  function digitValue(cp) {
    if (cp - 48 < 10) return cp - 22;        // 0-9
    if (cp - 65 < 26) return cp - 65;        // A-Z
    if (cp - 97 < 26) return cp - 97;        // a-z
    return BASE;
  }

  function adaptBias(delta, numPoints, firstTime) {
    delta = firstTime ? Math.floor(delta / DAMP) : delta >> 1;
    delta += Math.floor(delta / numPoints);
    var k = 0;
    while (delta > ((BASE - TMIN) * TMAX) >> 1) {
      delta = Math.floor(delta / (BASE - TMIN));
      k += BASE;
    }
    return k + Math.floor(((BASE - TMIN + 1) * delta) / (delta + SKEW));
  }

  function decodeLabel(input) {
    var output = [];
    var basic = input.lastIndexOf('-');
    if (basic > 0) {
      for (var j = 0; j < basic; j++) output.push(input.charCodeAt(j));
    }
    var n = INITIAL_N, bias = INITIAL_BIAS, i = 0;
    var index = basic > 0 ? basic + 1 : 0;

    while (index < input.length) {
      var oldi = i, w = 1, k = BASE;
      for (;;) {
        if (index >= input.length) return null;
        var digit = digitValue(input.charCodeAt(index++));
        if (digit >= BASE) return null;
        if (digit > Math.floor((0x7fffffff - i) / w)) return null;
        i += digit * w;
        var t = k <= bias ? TMIN : (k >= bias + TMAX ? TMAX : k - bias);
        if (digit < t) break;
        if (w > Math.floor(0x7fffffff / (BASE - t))) return null;
        w *= BASE - t;
        k += BASE;
      }
      var out = output.length + 1;
      bias = adaptBias(i - oldi, out, oldi === 0);
      if (Math.floor(i / out) > 0x7fffffff - n) return null;
      n += Math.floor(i / out);
      i %= out;
      output.splice(i++, 0, n);
    }
    var result = '';
    for (var c = 0; c < output.length; c++) result += String.fromCodePoint(output[c]);
    return result;
  }

  var __nodeUrl = {
    domainToUnicode: function (host) {
      if (!host) return '';
      return String(host).split('.').map(function (label) {
        if (label.slice(0, 4).toLowerCase() !== 'xn--') return label;
        var decoded = decodeLabel(label.slice(4));
        return decoded === null ? label : decoded;
      }).join('.');
    },
  };

  // --- minimal path, only what the engine touches --------------------------
  var __pathStub = {
    basename: function (p, ext) {
      var base = String(p).split(/[\\\\/]/).pop() || '';
      if (ext && base.slice(-ext.length) === ext) base = base.slice(0, -ext.length);
      return base;
    },
    extname: function (p) {
      var base = __pathStub.basename(p);
      var i = base.lastIndexOf('.');
      return i > 0 ? base.slice(i) : '';
    },
    join: function () { return Array.prototype.join.call(arguments, '/').replace(/\\/+/g, '/'); },
    dirname: function (p) { return String(p).replace(/\\/[^/]*$/, '') || '.'; },
    sep: '/',
    resolve: function () { return __pathStub.join.apply(null, arguments); },
    parse: function (p) { return { root: '/', base: __pathStub.basename(p) }; },
  };

  // Blocklists only touches the filesystem in load(), which the phone build
  // never calls: it ships the built-in seed lists and any list you paste in.
  var __fsStub = {
    existsSync: function () { return false; },
    readdirSync: function () { return []; },
    readFileSync: function () { return ''; },
    mkdirSync: function () {},
    writeFileSync: function () {},
    statSync: function () { throw new Error('no filesystem'); },
  };

  // --- SHA-256, synchronous ------------------------------------------------
  // scanner.js hashes files inline. SubtleCrypto is async and would mean
  // restructuring shared code for one platform, so the phone build carries a
  // compact synchronous implementation instead. Verified against known vectors
  // in test/mobile-engine.test.js.
  var K256 = (function () {
    var k = [], primes = [], n = 2;
    function isPrime(x) { for (var i = 2; i * i <= x; i++) if (x % i === 0) return false; return true; }
    while (primes.length < 64) { if (isPrime(n)) primes.push(n); n++; }
    for (var i = 0; i < 64; i++) {
      k.push(Math.floor((Math.pow(primes[i], 1 / 3) % 1) * Math.pow(2, 32)) >>> 0);
    }
    return k;
  }());

  function sha256Hex(bytes) {
    var h = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
             0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
    var len = bytes.length;
    var withPad = new Uint8Array((((len + 8) >> 6) + 1) << 6);
    withPad.set(bytes);
    withPad[len] = 0x80;
    var bitLenHi = Math.floor(len / 0x20000000);
    var bitLenLo = (len << 3) >>> 0;
    var dv = new DataView(withPad.buffer);
    dv.setUint32(withPad.length - 8, bitLenHi, false);
    dv.setUint32(withPad.length - 4, bitLenLo, false);

    var w = new Uint32Array(64);
    for (var off = 0; off < withPad.length; off += 64) {
      for (var i = 0; i < 16; i++) w[i] = dv.getUint32(off + i * 4, false);
      for (i = 16; i < 64; i++) {
        var g0 = w[i - 15], g1 = w[i - 2];
        var s0 = ((g0 >>> 7) | (g0 << 25)) ^ ((g0 >>> 18) | (g0 << 14)) ^ (g0 >>> 3);
        var s1 = ((g1 >>> 17) | (g1 << 15)) ^ ((g1 >>> 19) | (g1 << 13)) ^ (g1 >>> 10);
        w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0;
      }
      var a = h[0], b = h[1], c = h[2], d = h[3], e = h[4], f = h[5], g = h[6], hh = h[7];
      for (i = 0; i < 64; i++) {
        var S1 = ((e >>> 6) | (e << 26)) ^ ((e >>> 11) | (e << 21)) ^ ((e >>> 25) | (e << 7));
        var ch = (e & f) ^ (~e & g);
        var t1 = (hh + S1 + ch + K256[i] + w[i]) >>> 0;
        var S0 = ((a >>> 2) | (a << 30)) ^ ((a >>> 13) | (a << 19)) ^ ((a >>> 22) | (a << 10));
        var maj = (a & b) ^ (a & c) ^ (b & c);
        var t2 = (S0 + maj) >>> 0;
        hh = g; g = f; f = e; e = (d + t1) >>> 0;
        d = c; c = b; b = a; a = (t1 + t2) >>> 0;
      }
      h[0] = (h[0] + a) >>> 0; h[1] = (h[1] + b) >>> 0;
      h[2] = (h[2] + c) >>> 0; h[3] = (h[3] + d) >>> 0;
      h[4] = (h[4] + e) >>> 0; h[5] = (h[5] + f) >>> 0;
      h[6] = (h[6] + g) >>> 0; h[7] = (h[7] + hh) >>> 0;
    }
    var out = '';
    for (var j = 0; j < 8; j++) out += ('00000000' + h[j].toString(16)).slice(-8);
    return out;
  }

  var __cryptoStub = {
    createHash: function (algo) {
      var chunks = [];
      return {
        update: function (b) { chunks.push(__toBytes(b)); return this; },
        digest: function () {
          if (String(algo).toLowerCase() !== 'sha256') return null;
          var total = 0, i;
          for (i = 0; i < chunks.length; i++) total += chunks[i].length;
          var all = new Uint8Array(total), o = 0;
          for (i = 0; i < chunks.length; i++) { all.set(chunks[i], o); o += chunks[i].length; }
          return sha256Hex(all);
        },
      };
    },
    randomBytes: function (n) {
      var a = new Uint8Array(n);
      if (root.crypto && root.crypto.getRandomValues) root.crypto.getRandomValues(a);
      return { toString: function () {
        return Array.prototype.map.call(a, function (b) { return ('0' + b.toString(16)).slice(-2); }).join('');
      } };
    },
  };

  // --- Buffer, only the surface scanner.js uses -----------------------------
  function __toBytes(v) {
    if (v instanceof Uint8Array) return v;
    if (typeof v === 'string') return __ShadowBuffer.from(v, 'latin1');
    return new Uint8Array(v || 0);
  }

  function __decodeLatin1(bytes) {
    var out = '', CHUNK = 0x8000;
    for (var i = 0; i < bytes.length; i += CHUNK) {
      out += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
    }
    return out;
  }

  function __decodeUtf16le(bytes) {
    var out = '', CHUNK = 0x8000;
    var units = new Uint16Array(bytes.buffer, bytes.byteOffset, Math.floor(bytes.length / 2));
    for (var i = 0; i < units.length; i += CHUNK) {
      out += String.fromCharCode.apply(null, units.subarray(i, i + CHUNK));
    }
    return out;
  }

  var __utf8Decoder = typeof TextDecoder !== 'undefined' ? new TextDecoder('utf-8') : null;

  function __augment(bytes) {
    if (bytes.__shadowBuf) return bytes;
    Object.defineProperties(bytes, {
      __shadowBuf: { value: true },
      readUInt8: { value: function (o) { return this[o]; } },
      readUInt16LE: { value: function (o) { return this[o] | (this[o + 1] << 8); } },
      readUInt16BE: { value: function (o) { return (this[o] << 8) | this[o + 1]; } },
      readUInt32LE: { value: function (o) {
        return ((this[o]) | (this[o + 1] << 8) | (this[o + 2] << 16)) + (this[o + 3] * 0x1000000);
      } },
      readUInt32BE: { value: function (o) {
        return (this[o] * 0x1000000) + ((this[o + 1] << 16) | (this[o + 2] << 8) | this[o + 3]);
      } },
      equals: { value: function (other) {
        if (this.length !== other.length) return false;
        for (var i = 0; i < this.length; i++) if (this[i] !== other[i]) return false;
        return true;
      } },
      subarray: { value: function (a, b) {
        return __augment(Uint8Array.prototype.subarray.call(this, a, b));
      } },
      slice: { value: function (a, b) {
        return __augment(Uint8Array.prototype.subarray.call(this, a, b));
      } },
      toString: { value: function (enc) {
        var e = String(enc || 'utf8').toLowerCase();
        if (e === 'latin1' || e === 'binary') return __decodeLatin1(this);
        if (e === 'utf16le' || e === 'ucs2' || e === 'ucs-2') return __decodeUtf16le(this);
        if (e === 'hex') {
          var s = '';
          for (var i = 0; i < this.length; i++) s += ('0' + this[i].toString(16)).slice(-2);
          return s;
        }
        return __utf8Decoder ? __utf8Decoder.decode(this) : __decodeLatin1(this);
      } },
    });
    return bytes;
  }

  var __ShadowBuffer = {
    from: function (value, enc) {
      if (value instanceof Uint8Array) return __augment(new Uint8Array(value));
      if (typeof value === 'string') {
        var e = String(enc || 'utf8').toLowerCase();
        if (e === 'latin1' || e === 'binary') {
          var b = new Uint8Array(value.length);
          for (var i = 0; i < value.length; i++) b[i] = value.charCodeAt(i) & 0xff;
          return __augment(b);
        }
        return __augment(new TextEncoder().encode(value));
      }
      return __augment(new Uint8Array(value));
    },
    alloc: function (n, fill) {
      var b = new Uint8Array(n);
      if (fill) b.fill(typeof fill === 'number' ? fill : 0);
      return __augment(b);
    },
    concat: function (list) {
      var total = 0, i;
      for (i = 0; i < list.length; i++) total += list[i].length;
      var out = new Uint8Array(total), o = 0;
      for (i = 0; i < list.length; i++) { out.set(list[i], o); o += list[i].length; }
      return __augment(out);
    },
    isBuffer: function (v) { return v instanceof Uint8Array; },
  };
  root.__ShadowBuffer = __ShadowBuffer;

  // zlib is used only to inflate PDF object streams. There is no synchronous
  // inflate in a browser, so the phone build reports this honestly rather than
  // pretending a compressed stream was inspected.
  var __zlibStub = {
    inflateSync: function () { throw new Error('SHADOW_NO_ZLIB'); },
    unavailable: true,
  };

  __MODULES__

  // --- public surface -------------------------------------------------------
  var urlH = require('soc/heuristics/url-heuristics.js');
  var contentH = require('soc/heuristics/content-heuristics.js');
  var tlsH = require('soc/heuristics/tls-heuristics.js');
  var scoring = require('soc/scoring.js');
  var Blocklists = require('firewall/blocklists.js').Blocklists;
  var rules = require('firewall/rules.js');

  var blocklists = new Blocklists({});

  function hostOf(u) {
    try { return new URL(u).hostname.toLowerCase(); } catch (e) { return ''; }
  }

  function withBlocklist(signals, url) {
    var host = hostOf(url);
    if (!host) return signals;
    var hits = blocklists.match(host, url);
    for (var i = 0; i < hits.length; i++) {
      signals.push({
        id: 'blocklist.' + hits[i].list,
        score: hits[i].score,
        severity: hits[i].severity,
        title: hits[i].title,
        detail: hits[i].detail,
      });
    }
    return signals;
  }

  var scanner = require('sandbox/scanner.js');

  root.ShadowEngine = {
    version: '0.1.0',
    Buffer: __ShadowBuffer,
    sha256: function (bytes) { return sha256Hex(__toBytes(bytes)); },
    pdfStreamsInspected: false,   // no synchronous inflate in a browser
    analyzeUrl: urlH.analyzeUrl,
    analyzeContent: contentH.analyzeContent,
    analyzeCertificate: tlsH.analyzeCertificate,
    decide: scoring.decide,
    splitHost: urlH.splitHost,
    isLocalAddress: urlH.isLocalAddress,
    classifyHost: rules.classifyHost,
    blocklists: blocklists,

    /** URL signals plus blocklists, scored. The pre-navigation check. */
    checkUrl: function (url, opts) {
      opts = opts || {};
      var signals = withBlocklist(urlH.analyzeUrl(url), url);
      var verdict = scoring.decide(signals, opts);
      verdict.url = url;
      verdict.hostname = hostOf(url);
      return verdict;
    },

    /**
     * Scan file bytes with the same code the desktop sandbox runs.
     * @param {ArrayBuffer|Uint8Array} data
     * @param {object} meta { name, sourceUrl, mimeType }
     */
    scanBytes: function (data, meta) {
      meta = meta || {};
      var bytes = __ShadowBuffer.from(data instanceof ArrayBuffer ? new Uint8Array(data) : data);
      var name = meta.name || 'file.bin';

      var signals = scanner.checkFilename(name).signals;
      var detected = scanner.identify(bytes);
      var declaredExt = (String(name).toLowerCase().match(/\.[a-z0-9]{1,8}$/) || [''])[0];

      if (detected.type !== 'unknown' && detected.type !== 'text' && declaredExt
          && detected.ext.indexOf(declaredExt) === -1) {
        var executable = ['pe', 'elf', 'macho', 'lnk', 'class'].indexOf(detected.type) !== -1;
        signals.push({
          id: 'file.type-mismatch',
          score: executable ? 80 : 40,
          severity: executable ? 'critical' : 'medium',
          title: 'File claims to be "' + declaredExt + '" but is really ' + detected.type.toUpperCase(),
          detail: executable
            ? 'The content starts with a ' + detected.type.toUpperCase()
              + ' executable header. Whatever the name says, this is a program.'
            : 'Expected ' + declaredExt + ', found ' + detected.type + '. The name is misleading.',
        });
      }

      var formatInfo = {};
      var partial = [];
      try {
        if (detected.type === 'pe') {
          var pe = scanner.inspectPe(bytes);
          signals = signals.concat(pe.signals); formatInfo.pe = pe.info;
        } else if (detected.type === 'zip') {
          var zip = scanner.inspectZip(bytes, name);
          signals = signals.concat(zip.signals);
          formatInfo.zip = { entryCount: zip.info.entries.length, encrypted: zip.info.encrypted };
        } else if (detected.type === 'ole') {
          signals = signals.concat(scanner.inspectOle(bytes).signals);
        } else if (detected.type === 'pdf') {
          signals = signals.concat(scanner.inspectPdf(bytes).signals);
          partial.push('Compressed PDF streams were not decompressed: a browser has no synchronous inflate. '
            + 'Uncompressed actions were still checked. The desktop build inspects both.');
        } else if (detected.type === 'text') {
          var sc = scanner.inspectScript(bytes, declaredExt);
          signals = signals.concat(sc.signals); formatInfo.script = sc.info;
        }
      } catch (e) {
        signals.push({ id: 'scan.partial', score: 20, severity: 'low',
          title: 'Part of the file could not be parsed',
          detail: 'Shadow read what it could. ' + e.message });
      }

      var hits = scanner.scanStrings(bytes);
      for (var i = 0; i < hits.length; i++) {
        signals.push({
          id: 'strings.' + hits[i].label.replace(/\s+/g, '-').toLowerCase(),
          score: hits[i].score,
          severity: hits[i].score >= 70 ? 'critical' : (hits[i].score >= 45 ? 'high' : 'medium'),
          title: 'Contains ' + hits[i].label,
          detail: 'Matched: ' + String(hits[i].sample).replace(/\s+/g, ' ').slice(0, 140),
        });
      }

      var network = scanner.findEmbeddedNetworkIndicators(bytes);
      if (network.onion.length) {
        signals.push({ id: 'file.onion-c2', score: 45, severity: 'high',
          title: 'Hard-coded Tor address',
          detail: 'Found ' + network.onion[0] + '. Malware uses hidden services so its control server cannot be taken down.' });
      }

      var verdict = scoring.decide(signals, meta.opts || {});
      verdict.file = { name: name, size: bytes.length, sizeHuman: scanner.humanSize(bytes.length) };
      verdict.detectedType = detected.type;
      verdict.declaredExtension = declaredExt || null;
      verdict.hashes = { sha256: sha256Hex(bytes) };
      verdict.network = network;
      verdict.formatInfo = formatInfo;
      verdict.limitations = partial;
      return verdict;
    },

    /** Everything the desktop deep scan does, given the page HTML. */
    checkPage: function (html, url, opts) {
      opts = opts || {};
      var signals = urlH.analyzeUrl(url)
        .concat(contentH.analyzeContent(html, url))
        .concat(withBlocklist([], url));
      var verdict = scoring.decide(signals, opts);
      verdict.url = url;
      verdict.hostname = hostOf(url);
      return verdict;
    },
  };
}(typeof globalThis !== 'undefined' ? globalThis : this));
`;

  // A function replacement, not a string. In a string replacement "$&", "$`"
  // and friends are substitution patterns, and module source is full of
  // template literals like `.${suffix}` that would be silently mangled.
  const body = shim.replace('__MODULES__', () => parts.join('\n'));
  fs.writeFileSync(OUT, `${banner}\n${body}`);

  const bytes = fs.statSync(OUT).size;
  console.log(`built ${path.relative(process.cwd(), OUT)}  ${(bytes / 1024).toFixed(1)} KB  from ${MODULES.length} modules`);
  return OUT;
}

if (require.main === module) build();
module.exports = { build, MODULES };
